### ISSUE TITLE
SyntaxError: Setter must have exactly one formal parameter.

### ISSUE THREAD

**Issue by am2222** [mapbox/tilelive#207]
Hi,
When I tried to use `tilelive-copy` on `ubunto 16.04` I faced this error,
Is there any dependencies which I have not installed?

```
m@ubuntu:~/vtile/mapbox-gl-importer-master$ tilelive-copy
/usr/lib/nodejs/tilelive/lib/statistics.js:24
    set remaining() {}, // read-only
                 ^^

SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/nodejs/tilelive/lib/scheme.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by nnhubbard** [comment]
Did you ever figure out this issue? I have the same problem.
