### ISSUE TITLE
Option to skip and report, or improved logging of failed tiles.

### ISSUE THREAD

**Issue by agoddard** [mapbox/tilelive#225]
👋  When running `tilelive-copy --scheme=list --list=/list_of_tiles.txt` I occasionally see the following error, which stops tilelive-copy from any further processing of the `list_of_tiles.txt` list :

```
   if (err) throw err;
                 ^

TypeError: required parameters (z, x, and y) must be greater then or equal to zero
    at TypeError (native)
    at Function.Bridge.getVector (/usr/local/lib/node_modules/tilelive-bridge/index.js:243:21)
    at /usr/local/lib/node_modules/tilelive-bridge/index.js:185:20
    at dispense (/usr/local/lib/node_modules/tilelive-bridge/node_modules/generic-pool/lib/generic-pool.js:258:16)
    at Object.me.release (/usr/local/lib/node_modules/tilelive-bridge/node_modules/generic-pool/lib/generic-pool.js:368:5)
    at /usr/local/lib/node_modules/tilelive-bridge/index.js:282:21
```

I've inspected my tiles list a number of ways and I can't determine the problematic tile, so it would be helpful to have a `--skip-failed-tiles` flag, or similar, which would simply move on to the next tile (while outputting the failed tile info) and/or a `--debug` / `--verbose` flag to print out the current tile that's being processed, so it's easier to debug when this case occurs.

I can work on a PR for either/both, would love opinions on whether this approach would be sensible/helpful.

Thanks!

**Comment by agoddard** [comment]
Looks like the error is raised by https://github.com/mapnik/node-mapnik/blob/32a3e453e6afe3cc994a203fdcbd3e5de614cfed/src/mapnik_vector_tile.cpp#L147
